Refactor and improve integration tests
- Refactored tests, improving cleanup logic
- Add 'run' script to run all available tests (output can be improved)

diff --git a/tests/00-http-docker-swarm/test b/tests/00-http-docker-swarm/test
--- a/tests/00-http-docker-swarm/test
+++ b/tests/00-http-docker-swarm/test
@@ -14,13 +14,7 @@ networks() {
   echo ''
 }
 
-quit() {
-  # Don't run a second time
-  trap '' TERM INT EXIT
-  
-  # Allow this to complete, even if we encounter errors
-  set +e
-
+_cleanup() {
   echo "> ($h) Cleaning up nodes ..."
   docker rm -f $(nodes) 2>/dev/null
   echo
@@ -46,6 +40,24 @@ quit() {
   echo
 
   echo "> ($h) Cleaned up"
+}
+
+cleanup() {
+  # Allow this to complete, even if we encounter errors
+  set +e
+
+  _cleanup
+  
+  # Restore setting to fail on error
+  set -e
+}
+
+quit() {
+  # Don't run a second time
+  trap '' TERM INT EXIT
+  
+  cleanup
+
   echo "> ($h) Exiting with code $ERRORS"
 }
 
@@ -53,19 +65,21 @@ trap quit TERM INT EXIT
 
 h=$(hostname)
 
+cleanup
+
 echo "> ($h) Build image ..."
 docker build --iidfile /tmp/iid -f node/Dockerfile node/
 
 IMAGE=$(cat /tmp/iid)
 
-echo "> ($h) Launch VM nodes with image $IMAGE ..."
+echo "> ($h) Launch RunCVM nodes with image $IMAGE ..."
 for n in 1 2 3
 do
-  docker run -d -it --runtime=runcvm -p $((8080+$n-1)):80 --rm --name=$NODE$n --hostname=$NODE$n --mount=type=volume,src=$NODE$n,dst=/var/lib/docker --env=RUNCVM_SYS_ADMIN=1 --mount=type=volume,src=swarm,dst=/swarm $IMAGE  
+  docker run --runtime=runcvm -d -p $((8080+$n-1)):80 --rm --name=$NODE$n --hostname=$NODE$n --mount=type=volume,src=$NODE$n,dst=/var/lib/docker --env=RUNCVM_SYS_ADMIN=1 --mount=type=volume,src=swarm,dst=/swarm $IMAGE  
 done
 
 echo "> ($h) Monitoring ${NODE}1 logs for service launch ..."
-docker logs -f ${NODE}1 | sed '/service launched/ q'
+docker logs -f ${NODE}1 | sed '/service launched/q'
 echo
 
 echo "> ($h) Monitoring ${NODE}1 logs ..."
diff --git a/tests/01-mariadb/test b/tests/01-mariadb/test
--- a/tests/01-mariadb/test
+++ b/tests/01-mariadb/test
@@ -14,13 +14,7 @@ networks() {
   echo $NODE-network
 }
 
-quit() {
-  # Don't run a second time
-  trap '' TERM INT EXIT
-  
-  # Allow this to complete, even if we encounter errors
-  set +e
-
+_cleanup() {
   echo "> ($h) Cleaning up nodes ..."
   docker rm -f $(nodes) 2>/dev/null
   echo
@@ -46,6 +40,24 @@ quit() {
   echo
 
   echo "> ($h) Cleaned up"
+}
+
+cleanup() {
+  # Allow this to complete, even if we encounter errors
+  set +e
+
+  _cleanup
+  
+  # Restore setting to fail on error
+  set -e
+}
+
+quit() {
+  # Don't run a second time
+  trap '' TERM INT EXIT
+  
+  cleanup
+
   echo "> ($h) Exiting with code $ERRORS"
 }
 
@@ -53,12 +65,15 @@ trap quit TERM INT EXIT
 
 h=$(hostname)
 
+cleanup
+
 echo "> ($h) Creating network $NODE-network ..."
 docker network rm $(networks) 2>/dev/null || true
 docker network create $NODE-network
 
-echo "> ($h) Launch CVM mariadb server as $NODE-mysqld ..."
-docker run -d -it --rm --runtime=runcvm --name=$NODE-mysqld --hostname=$NODE-mysqld --network=$NODE-network --cpus=1 --memory=512M --env=MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1 mariadb
+# Launch a mariadb VM using RunCVM
+echo "> ($h) Launch RunCVM mariadb server as $NODE-mysqld ..."
+docker run --runtime=runcvm -d --rm --name=$NODE-mysqld --hostname=$NODE-mysqld --network=$NODE-network --cpus=1 --memory=1G --env=MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1 mariadb
 
 echo "> ($h) Monitoring mariadb logs ..."
 docker logs -f -t -n 0 $NODE-mysqld &
@@ -66,11 +81,14 @@ docker logs -f -t -n 0 $NODE-mysqld &
 # Allow final test to complete, even if we encounter errors
 set +e
 
-echo "> ($h) Waiting for mariadb startup and running test queries ..."
-docker run -it --rm --network=$NODE-network --name=$NODE-mysql --hostname=$NODE-mysql --env=host=$NODE-mysqld alpine ash -c 'apk update && apk add mariadb-client && for a in $(seq 20 -1 1); do if mysql -P 3306 -h $host mysql -e ""; then echo "> $(hostname) Connected to mysqld ..."; break; else echo "> $(hostname) Waiting for mysqld (#$a) ..."; sleep 1; fi; done && mysql -P 3306 -h $host mysql -e "select count(*) from user"'
+# Launch standard runc container to test connecting to the mariadb VM
+echo "> ($h) Waiting for mariadb startup and running test queries in runc container ..."
+docker run --rm --network=$NODE-network --name=$NODE-mysql --hostname=$NODE-mysql --env=host=$NODE-mysqld alpine ash -c 'apk update && apk add mariadb-client && for a in $(seq 40 -1 1); do if mysql -P 3306 -h $host mysql -e ""; then echo "> $(hostname) Connected to mysqld ..."; break; else echo "> $(hostname) Waiting for mysqld (#$a) ..."; sleep 1; fi; done && mysql -P 3306 -h $host mysql -e "select count(*) from user"'
 ERRORS=$?
 
 echo "> ($h) Completed $NODE test with $ERRORS errors"
+
+# bash -i
 
 sleep 1
 exit $ERRORS
