Refactor docker swarm test and add support for modified MTU
- RunCVM nodes are launched on a custom network with a custom MTU
- Nodes detect their MTU, then launch dockerd --mtu accordingly
- Nodes create their own docker_gwbridge network with custom MTU
- After swarm init, primary node recreates ingress network
- Refactored test simplifies and standardises in-node docker.sh logic

diff --git a/tests/00-http-docker-swarm/test b/tests/00-http-docker-swarm/test
--- a/tests/00-http-docker-swarm/test
+++ b/tests/00-http-docker-swarm/test
@@ -1,9 +1,17 @@
 #!/bin/bash -e
 
 NODE=00-http-docker-swarm-node
+NODES=3
+MTU=9000
+
+log() {
+  local opts
+  if [ "$1" = "-n" ]; then opts="-n"; shift; fi
+  echo $opts "($h) > $1"
+}
 
 nodes() {
-  seq 1 3 | sed "s/^/$NODE/"
+  seq 1 $NODES | sed "s/^/$NODE/"
 }
 
 volumes() {
@@ -11,22 +19,22 @@ volumes() {
 }
 
 networks() {
-  echo ''
+  echo runcvm-mtu
 }
 
 _cleanup() {
-  echo "> ($h) Cleaning up nodes ..."
+  log "Cleaning up nodes ..."
   docker rm -f $(nodes) 2>/dev/null
   echo
 
   if [ "$(volumes)" != "" ]; then
-    echo "> ($h) Cleaning up volumes ..."
+    log "Cleaning up volumes ..."
     docker volume rm -f $(volumes)
   fi
   echo
 
   if [ -n "$IMAGE" ]; then
-    echo "> ($h) Cleaning up temporary image ..."
+    log "Cleaning up temporary image ..."
     docker rmi $IMAGE
     echo
   fi
@@ -34,12 +42,12 @@ _cleanup() {
   rm -f /tmp/iid
   
   if [ "$(networks)" != "" ]; then
-    echo "> ($h) Cleaning up networks ..."
+    log "Cleaning up networks ..."
     docker network rm $(networks)
   fi
   echo
 
-  echo "> ($h) Cleaned up"
+  log "Cleaned up"
 }
 
 cleanup() {
@@ -53,13 +61,17 @@ cleanup() {
 }
 
 quit() {
+  local code=$?
+
   # Don't run a second time
   trap '' TERM INT EXIT
   
   cleanup
 
-  echo "> ($h) Exiting with code $ERRORS"
+  log "Exiting with code $code"
 }
+
+# Standard setup
 
 trap quit TERM INT EXIT
 
@@ -67,45 +79,104 @@ h=$(hostname)
 
 cleanup
 
-echo "> ($h) Build image ..."
+log "Build image ..."
 docker build --iidfile /tmp/iid -f node/Dockerfile node/
-
 IMAGE=$(cat /tmp/iid)
 
-echo "> ($h) Launch RunCVM nodes with image $IMAGE ..."
-for n in 1 2 3
+log "Creating network 'runcvm-mtu' with MTU $MTU ..."
+docker network create --opt com.docker.network.driver.mtu=$MTU --scope=local runcvm-mtu
+
+log "Launching $NODES x RunCVM nodes with image $IMAGE ..."
+for n in $(seq 1 $NODES)
 do
-  docker run --runtime=runcvm -d -p $((8080+$n-1)):80 --rm --name=$NODE$n --hostname=$NODE$n --mount=type=volume,src=$NODE$n,dst=/var/lib/docker --env=RUNCVM_SYS_ADMIN=1 --mount=type=volume,src=swarm,dst=/swarm $IMAGE  
+  log -n "Launching RunCVM node $n/$NODES ... "
+
+  diskopt="--mount=type=volume,src=$NODE$n,dst=/var/lib/docker"
+  # diskopt="--mount=type=volume,src=$NODE$n,dst=/disks --env=RUNCVM_DISKS=/disks/disk1,/var/lib/docker,ext4,1G"
+
+  # The swarm volume, mounted at /swarm within the RunCVM VMs, will be used to share swarm info
+  # among the nodes.
+  docker run \
+    -d \
+    --rm \
+    --runtime=runcvm \
+    --network=runcvm-mtu \
+    -p $((8080+$n-1)):80 \
+    --name=$NODE$n \
+    --hostname=$NODE$n \
+    --env=NODE=$n \
+    --env=NODES=$NODES \
+    --mount=type=volume,src=swarm,dst=/swarm \
+    $diskopt \
+    $IMAGE
 done
 
-echo "> ($h) Monitoring ${NODE}1 logs for service launch ..."
-docker logs -f ${NODE}1 | sed '/service launched/q'
-echo
+log "Monitoring ${NODE}1 logs for swarm setup progress ..."
+docker logs -f ${NODE}1 -n 0 2>&1 | sed "s/^/($h) > (${NODE}1) > /; /Swarm complete/q0; /Swarm failed/q129;"
+log "Finished monitoring ${NODE}1 logs as swarm is set up."
 
-echo "> ($h) Monitoring ${NODE}1 logs ..."
-docker logs -f -t -n 0 ${NODE}1 &
-echo
+log "Creating http service (please be patient) ..."
+docker exec ${NODE}1 docker service create \
+  -d \
+  --name=http --mode=global -p 80:80 --update-parallelism=0 \
+  alpine ash -c "$(tr '\012' ' ' <<_EOE_
+apk add --no-cache mini_httpd &&
+mkdir -p /www &&
+echo -e "#!/bin/sh\n\necho Content-Type: text/plain\necho\necho hostname=\$HOSTNAME remote_addr=\\\$REMOTE_ADDR\nexit 0\n" >/www/index.cgi &&
+chmod 755 /www/index.cgi &&
+mini_httpd -d /www -D -l /dev/stdout -c '**.cgi'
+_EOE_
+)"
 
-sleep 3
+for i in $(seq 1 20 | sort -nr)
+do
+  replicas=$(docker exec ${NODE}1 docker service ls --format='{{ .Replicas }}' --filter='Name=http')
+  log "Waiting for remainder of $replicas replicas to launch (#$i) ..."
+  [ "$replicas" = "$NODES/$NODES" ] && break
+  [ $i -eq 1 ] && exit 130
+  sleep 1
+done
+log "All $NODES replicas launched."
+sleep 1
 
 # Allow final test to complete, even if we encounter errors
 set +e
 
-echo "> ($h) Running $NODE test ..."
+DOCKER_IPV4="10.0.0."
+
+log "Running $NODE test looking for $DOCKER_IPV4 at $(date) ..."
 ERRORS=0
 TESTS=0
-for loop in $(seq 1 10)
+for loop in $(seq 1 250)
 do
-  for a in $(nodes)
-  do
-    curl -s http://0.0.0.0:8080/ | grep '<title>hostname'
-    ERRORS=$((ERRORS+$?))
-    TESTS=$((TESTS+1))
-  done
-done
-echo
+  i=$((loop % NODES))
 
-echo "> ($h) Completed $NODE test $TESTS times, with $ERRORS errors"
+  host=http://0.0.0.0:$((8080+i))/
+
+  # Uncomment if running inside a Dockside devtainer (which must be preconnected to a precreated runcvm-mtu Docker network).
+  # host=http://$NODE$((i+1)):80/
+
+  response=$(curl -is $host)
+  ERROR=$?
+
+  if [ $ERROR -eq 0 ]; then
+    response=$(tr '\012\015' '  ' <<<$response)
+    grep -q "remote_addr=$DOCKER_IPV4" <<<$response
+    [ $? -ne 0 ] && log "#$loop Response error: $response" && ERROR=1
+  else
+    log "#$loop Response error: curl error $ERROR"
+    ERROR=1
+  fi
+
+  ERRORS=$((ERRORS+ERROR))
+  TESTS=$((TESTS+1))
+
+done
+
+log "Completed $NODE test $TESTS times, with $ERRORS errors"
+
+# Uncomment to debug:
+# log "Falling to shell, type CTRL+D to exit and clean up"; bash -i
 
 sleep 1
 exit $ERRORS
